# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-takeoff

# >> macros
# << macros

Summary:    Takeoff
Version:    0.2.4
Release:    1
Group:      Qt/Qt
License:    GPLv3
URL:        https://github.com/black-sheep-dev/harbour-takeoff
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-takeoff.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Takeoff is an autostart manager for native Sailfish apps


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
%post
systemctl-user stop org.nubecula.takeoff.service || true
if /sbin/podof harbour-takeoff > /dev/null; then
killall harbour-takeoff || true
fi

if [[ ! -d "/home/nemo/.config/harbour-takeoff" ]]
then
mkdir /home/nemo/.config/harbour-takeoff
echo "#!/bin/bash" >> /home/nemo/.config/harbour-takeoff/takeoff.sh
chown -R nemo:nemo /home/nemo/.config/harbour-takeoff
chmod a+x /home/nemo/.config/harbour-takeoff/takeoff.sh
fi

systemctl restart mce.service
systemctl-user restart ngfd.service

systemctl-user daemon-reload
systemctl-user enable org.nubecula.takeoff.service || true

# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%preun
# >> preun
systemctl-user stop org.nubecula.takeoff.service || true
systemctl-user disable org.nubecula.takeoff.service || true
systemctl-user daemon-reload
if /sbin/pidof harbour-takeoff > /dev/null; then
killall harbour-takeoff || true
fi
# << preun

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_libdir}/systemd/user/org.nubecula.takeoff.service
%{_datadir}/%{name}/translations
# >> files
# << files
